### ISSUE TITLE
Bad state: Future already completed

### ISSUE THREAD

**Issue by lzhAndroid** [Baseflow/flutter_cache_manager#400]
Bad state: Future already completed
0      _AsyncCompleter.complete (dart:async/future_impl.dart:35:31)
#1      _decodeImage.<anonymous closure> (package:flutter_cache_manager/src/cache_managers/image_cache_manager.dart:161:15)
#2      ImageStreamCompleter.setImage (package:flutter/src/painting/image_stream.dart:655:25)
#3      MultiFrameImageStreamCompleter._emitFrame (package:flutter/src/painting/image_stream.dart:998:5)
#4      MultiFrameImageStreamCompleter._handleAppFrame (package:flutter/src/painting/image_stream.dart:922:7)
#5      MultiFrameImageStreamCompleter._handleAppFrame (package:flutter/src/painting/image_stream.dart:915:3)
#6      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1289:15)
#7      SchedulerBinding.handleBeginFrame.<anonymous closure> (package:flutter/src/scheduler/binding.dart:1140:11)
#8      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:625:13)
#9      SchedulerBinding.handleBeginFrame (package:flutter/src/scheduler/binding.dart:1138:17)
#10     SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:1055:5)
#11     SchedulerBinding._handleBeginFrame (package:flutter/src/scheduler/binding.dart:1046:3)
#12     _rootRunUnary (dart:async/zone.dart:1414:13)
#13     _rootRunUnary (dart:async/zone.dart:1404:1)
#14     _CustomZone.runUnary (dart:async/zone.dart:1307:19)
#15     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1216:7)
#16     _invoke1 (dart:ui/hooks.dart:166:10)
#17     PlatformDispatcher._beginFrame (dart:ui/platform_dispatcher.dart:316:5)
#18     _beginFrame (dart:ui/hooks.dart:101:31)
#19     _beginFrame (dart:ui/hooks.dart:99:1)

**Comment by cq-z** [comment]
me too 
<img width="532" alt="image" src="https://user-images.githubusercontent.com/3038490/218785457-5e1e2081-9038-43ac-8b87-6531a1bf8bd1.png">
<img width="353" alt="image" src="https://user-images.githubusercontent.com/3038490/218785594-7b8bc3ef-f29f-45b3-9a98-a92f3a781b7d.png">

**Comment by kirill-21** [comment]
![image](https://github.com/Baseflow/flutter_cache_manager/assets/63228361/7857c276-bce6-4522-a8bc-6d58639f5de3)
Same

**Comment by kirill-21** [comment]
This is related to maxWidthDiskCache & maxHeightDiskCache, i can reproduce this issue if placing a lot of images to a gridview.builder and specifying this variables

**Comment by shilishihe** [comment]
Has anyone managed to solve this problem?
